// <auto-generated />
namespace Cookit_Testing_zmh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recipeall : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recipeall));
        
        string IMigrationMetadata.Id
        {
            get { return "201809240804580_recipe-all"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
